[package]
name = "modul"
version = "0.1.0"
authors = ["zehreken <zehreken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.15.0"
nannou_audio = "0.15.0"
hound = "3.4.0"
ringbuf = "0.2.2"
cpal = "0.13.1"
