[package]
name = "modul"
version = "0.1.0"
authors = ["zehreken <zehreken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.15.0"
hound = "3.4.0"
ringbuf = "0.2.3"
cpal = "0.13.1"
eframe = "0.10.0"
miniquad = { version = "=0.3.0-alpha.27" }
egui-miniquad = "0.1.0"
egui = "0.10.0"
# https://github.com/not-fl3/miniquad/issues/172
[target.'cfg(target_os = "macos")'.dependencies]
copypasta = "0.7"